default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Root@123

development:
  <<: *default
  database: account_api_development

test:
  <<: *default
  database: account_api_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: account_api_production
  username: account_api
  password: <%= ENV["ACCOUNT_API_DATABASE_PASSWORD"] %>
